// <auto-generated />
using System;
using MenuApp.InventoryService.Persistance.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace MenuApp.InventoryService.Persistance.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20210531085931_bugfix")]
    partial class bugfix
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 64)
                .HasAnnotation("ProductVersion", "5.0.5");

            modelBuilder.Entity("MenuApp.InventoryService.Logic.Entity.Ingredient", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<int>("AmountNeeded")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Ingredients");
                });

            modelBuilder.Entity("MenuApp.InventoryService.Logic.Entity.IngredientNeeded", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<int>("AmountNeeded")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .HasColumnType("longtext");

                    b.Property<Guid?>("RecipeId")
                        .HasColumnType("char(36)");

                    b.HasKey("Id");

                    b.HasIndex("RecipeId");

                    b.ToTable("IngredientsNeeded");
                });

            modelBuilder.Entity("MenuApp.InventoryService.Logic.Entity.Recipe", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("Title")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Recipes");
                });

            modelBuilder.Entity("MenuApp.InventoryService.Logic.Entity.IngredientNeeded", b =>
                {
                    b.HasOne("MenuApp.InventoryService.Logic.Entity.Recipe", null)
                        .WithMany("IngredientsNeeded")
                        .HasForeignKey("RecipeId");
                });

            modelBuilder.Entity("MenuApp.InventoryService.Logic.Entity.Recipe", b =>
                {
                    b.Navigation("IngredientsNeeded");
                });
#pragma warning restore 612, 618
        }
    }
}
