name: ci

on:
  push:
    branches:
      - 'master'

jobs:
  tests:
    name: Integration Tests
    runs-on: self-hosted
    env:
      connectionString: ${{secrets.CONNECTIONSTRING}}
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '5.x.x'         
      - run: dotnet test
      
  docker:
    needs: tests
    runs-on: self-hosted
    steps:
      -
        name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: s3software/inventoryservice:latest
      -
        name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}
